global:
  scrape_interval: 5s

scrape_configs:
  # 기본 Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # DEV 서버 Node Exporter
  - job_name: 'node_exporter_dev'
    static_configs:
      - targets: ['13.54.10.35:9100']
  - job_name: 'jmeter'
    static_configs:
      - targets: ['jmeter:9271']
